# Generated by Django 4.1 on 2023-01-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name=['%Y-%m-%d %H:%M']),
        ),
    ]
