# Generated by Django 4.1 on 2023-01-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_userfollowing_following_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
