# Generated by Django 4.1 on 2023-01-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_userfollowing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
