# Generated by Django 4.1 on 2023-01-06 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_like_user_follow_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='userInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
