# Generated by Django 4.1 on 2023-01-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_like_post_remove_like_user_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likesNumber',
        ),
    ]
